# Generated by Django 4.0 on 2021-12-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField(blank=True)),
                ('last_active_moment', models.DateTimeField(auto_now=True)),
                ('created_moment', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['-created_moment'],
            },
        ),
        migrations.CreateModel(
            name='GlobalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messanger.profile')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
