# Generated by Django 4.0 on 2021-12-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
