# Generated by Django 4.0 on 2022-01-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='messanger.Profile'),
        ),
    ]
