# Generated by Django 4.0 on 2022-01-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0003_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('file', models.FileField(blank=True, upload_to='files/')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to='messanger.Profile')),
                ('messages', models.ManyToManyField(to='messanger.ChatMessage')),
            ],
        ),
    ]
